### ISSUE TITLE
How to buy PCB & PCBA

### ISSUE THREAD

**Issue by Ivy-Mo** [LouDnl/USBSID-Pico#7]
It’s Ivy from WellerPCB,we help you turn your designs into real objects PCB&PCBA, and we want to work with you over the long term, starting with samples.We sincerely looking for solution that bring you potential benefits.

I'll let you know the ordering process and hopefully help some of you who want to order.

If you want to buy first you have to know the price:
1. For PCB, you need to provide Gerber file. For PCBA, you need to provide Gerber file and BOM list.
2. Send these files to ivy@wellerpcb.com and wait for the offer to be completed., this will take about 1-2 days, if the  specifications needed for the quotation are missing such as the information of the stacked structure and the impedance information, we will contact you as soon as possible, please don't worry.

Price difference:
If you feel that there is a certain difference with other supplier's quotation may be due to the following factors.
1. Machine bonding and hand soldering: the former will be more expensive, but ensure the stability of the soldering, which is important for high quality requirements of the project.
2. No replacement components: some suppliers will replace your components with other brands of poorer quality components, or the use of fake components, high risk.
3. Different processing standards and quality: Each supplier has different production standards, if it is a case of distrust, the best way is to visit the factory and understand the production process.

Place an order:
Make sure you have the following documents before officially produce.
1. Gerber document
2. BOM list
3. Stencil file
4. Coordinate file
5. Silk-screen bitmap

Shipment Confirmation:
Declare the amount and shipping address

Waiting for logistics delivery:
Receive PCB & PCBA ;)

Hope this helps, all the best with the design!

**Comment by LouDnl** [comment]
Thanks for the tip, but PCBWay is just fine for now.
